### ISSUE TITLE
This Menger Sponge generator does not work on Blender 2.79

### ISSUE THREAD

**Issue by enzyme69** [sugiany/blender_menger_sponge#2]
Whenever I trigger the add Menger Sponge, I am getting:

```python
Traceback (most recent call last):
  File "/add_menger_sponge.py", line 196, in execute
    object_utils.object_data_add(context, mesh, operator=self)
  File "/Applications/Blender_X/blender.app/Contents/Resources/2.79/scripts/modules/bpy_extras/object_utils.py", line 143, in object_data_add
    if operator is not None and any(operator.layers):
  File "/Applications/Blender_X/blender.app/Contents/Resources/2.79/scripts/modules/bpy_types.py", line 605, in __getattribute__
    return super().__getattribute__(attr)
AttributeError: 'AddMengerSponge' object has no attribute 'layers'

location: <unknown location>:-1

```
